from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from campusconnect import views

urlpatterns = [
    path('admin/',                              admin.site.urls),
    path('',                                    views.home,               name='home'),
    path('login/',                              views.login_page,         name='login'),
    path('signup/',                             views.signup_page,        name='signup'),
    path('logout/',                             views.logout_page,        name='logout'),
    path('dashboard/',                          views.dashboard,          name='dashboard'),
    path('study/',                              views.study,              name='study'),
    path('announcements/',                      views.announcements,      name='announcements'),
    path('announcements/post/',                 views.post_announcement,  name='post_announcement'),
    path('announcements/edit/<int:pk>/',        views.edit_announcement,  name='edit_announcement'),
    path('announcements/delete/<int:pk>/',      views.delete_announcement,name='delete_announcement'),
    path('profile/',                            views.profile_view,       name='profile'),
    path('profile/edit/',                       views.edit_profile,       name='edit_profile'),
    path('study/compiler/', views.compiler, name='compiler'),
    path('study/goals/',                        views.goals,             name='goals'),
    path('study/goals/create/',                 views.create_goal,       name='create_goal'),
    path('study/goals/<int:goal_id>/',          views.goal_detail,       name='goal_detail'),
    path('study/goals/<int:goal_id>/submissions/', views.goal_submissions, name='goal_submissions'),
    path('study/goals/submission/<int:sub_id>/review/', views.review_submission, name='review_submission'),
    path('study/goals/<int:goal_id>/delete/',   views.delete_goal,       name='delete_goal'),
    path('study/chatbot/', views.chatbot, name='chatbot'),
    path('study/chatbot/api/', views.chatbot_api, name='chatbot_api'),
    path('library/', views.library, name='library'),
    path('library/mark-returned/<int:record_id>/', views.mark_returned, name='mark_returned'),
    path('library/penalty/<int:record_id>/', views.penalty_api, name='penalty_api'),
    path('study/compiler/',                     views.compiler,           name='compiler'),
    path('study/goals/',                        views.goals,              name='goals'),
    path('study/goals/create/',                 views.create_goal,        name='create_goal'),
    path('study/goals/<int:goal_id>/',          views.goal_detail,        name='goal_detail'),
    path('study/goals/<int:goal_id>/submissions/', views.goal_submissions, name='goal_submissions'),
    path('study/goals/submission/<int:sub_id>/review/', views.review_submission, name='review_submission'),
    path('study/goals/<int:goal_id>/delete/',   views.delete_goal,        name='delete_goal'),
    path('study/chatbot/',                      views.chatbot,            name='chatbot'),
    path('study/chatbot/api/',                  views.chatbot_api,        name='chatbot_api'),
    path('resources/',                          include('resources.urls')),
    path('study/self-study/', views.self_study, name='self_study'),
path('study/self-study/<int:resource_id>/', views.self_study_workspace, name='self_study_workspace'),
path('study/rag-chat/<int:resource_id>/', views.rag_chatbot_api, name='rag_chatbot_api'),
# ── Complaint Portal ──────────────────────────────────────
path('study/complaints/',                           views.complaint_portal,        name='complaint_portal'),
path('study/complaints/student/',                   views.complaint_student,       name='complaint_student'),
path('study/complaints/faculty/',                   views.complaint_faculty,       name='complaint_faculty'),
path('study/complaints/edit/<int:complaint_id>/',   views.complaint_edit,          name='complaint_edit'),
path('study/complaints/delete/<int:complaint_id>/', views.complaint_delete,        name='complaint_delete'),
path('study/complaints/status/<int:complaint_id>/', views.complaint_update_status, name='complaint_update_status'),
#------permission portal ________________
path('study/permission/',                           views.permission_portal,        name='permission_portal'),
path('study/permission/student/',                   views.permission_student,       name='permission_student'),
path('study/permission/faculty/',                   views.permission_faculty,       name='permission_faculty'),
path('study/permission/edit/<int:permission_id>/',   views.permission_edit,          name='permission_edit'),
path('study/permission/delete/<int:permission_id>/', views.permission_delete,        name='permission_delete'),
path('study/permission/status/<int:permission_id>/', views.permission_update_status, name='permission_update_status'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)