# Generated by Django 5.2.11 on 2026-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusconnect', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_branch',
            field=models.CharField(choices=[('all', 'All Branches'), ('aiml', 'AI & ML'), ('cse', 'CSE'), ('csd', 'CSD'), ('cst', 'CST'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE'), ('ce', 'Civil Engineering'), ('me', 'Mechanical')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_stream',
            field=models.CharField(choices=[('all', 'All Streams'), ('computing', 'Computing'), ('non-computing', 'Non-Computing')], default='all', max_length=15),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_year',
            field=models.CharField(choices=[('all', 'All Years'), ('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('aiml', 'AI & ML'), ('cse', 'CSE'), ('csd', 'CSD'), ('cst', 'CST'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE'), ('ce', 'Civil Engineering'), ('me', 'Mechanical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codechef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True),
        ),
    ]
