# Generated by Django 5.2.11 on 2026-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusconnect', '0003_announcement_target_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ece', 'Electronics & Communication'), ('eee', 'Electrical & Electronics'), ('ce', 'Civil Engineering'), ('me', 'Mechanical Engineering'), ('maths', 'Mathematics'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('eng', 'English'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects_teaching',
            field=models.TextField(blank=True, help_text='Comma-separated list of subjects', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
