# Generated by Django 5.2.11 on 2026-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusconnect', '0008_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
