# Generated by Django 6.0.2 on 2026-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(choices=[('OOPS', 'OOPs Through Java'), ('ADS', 'ADS'), ('DMGT', 'DM & GT'), ('UHV', 'UHV'), ('AI', 'AI'), ('Python', 'Python')], max_length=100),
        ),
    ]
